spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: zxcvbnm123
server:
  port: 8081

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
